### ISSUE TITLE
set up auto-publishing jsdocs

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/web-science#6]

**Comment by jonathanmayer** [comment]
@rhelmer Some thoughts on the JSDoc config, in no particular order...

- We should probably ignore content scripts (`*.content.js`), since they don't expose any external APIs (i.e., are effectively private to the library).
- We should also probably ignore the `webScience` namespace assembly script (`webScience.js`), since it's just internal plumbing for the library. We can document how to use the library (e.g., `import * as webScience from "@mozilla/web-science"` or `import { fooApi } from "@mozilla/web-science`) in the README.
- The JSDoc configs for `news-disinformation-study` and `rally-study-01` use the output directory `docs` rather than  `jsdocs`. Not sure what the right convention is. Probably doesn't matter.

Otherwise LGTM.
